#!/bin/bash

echo "--------------------------------------------"
echo "         Analyse lexicale en cours...       "
echo "--------------------------------------------"
flex lex$1.lex && gcc -o lex$1 lex.yy.c -lfl && ./lex$1 exemple$1.txt
echo "--------------------------------------------"
echo "         Fin de l'analyse lexicale.         "
echo "--------------------------------------------"
